2024-01-06 14:44:12,526 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-06 14:44:12,526 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Configure stats pid to 61646
2024-01-06 14:44:12,526 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Loading settings from /Users/curtispond/.config/wandb/settings
2024-01-06 14:44:12,526 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Loading settings from /Users/curtispond/Documents/wandb/wandb/settings
2024-01-06 14:44:12,526 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-06 14:44:12,527 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-06 14:44:12,527 INFO    MainThread:61646 [wandb_init.py:_log_setup():524] Logging user logs to /Users/curtispond/Documents/wandb/wandb/run-20240106_144412-xyyykjjm/logs/debug.log
2024-01-06 14:44:12,527 INFO    MainThread:61646 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/curtispond/Documents/wandb/wandb/run-20240106_144412-xyyykjjm/logs/debug-internal.log
2024-01-06 14:44:12,527 INFO    MainThread:61646 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x2826d38e0>
2024-01-06 14:44:12,528 INFO    MainThread:61646 [wandb_init.py:init():564] calling init triggers
2024-01-06 14:44:12,528 INFO    MainThread:61646 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning': 'marketing-analytics', 'task': 'classification'}
2024-01-06 14:44:12,528 INFO    MainThread:61646 [wandb_init.py:init():589] re-initializing run, found existing run on stack: wf6xw9ej
2024-01-06 14:44:12,529 INFO    MainThread:61646 [wandb_run.py:_finish():1962] finishing run curtis-pond/marketing-analysis/wf6xw9ej
2024-01-06 14:44:12,529 INFO    MainThread:61646 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-06 14:44:12,529 INFO    MainThread:61646 [wandb_run.py:_restore():2185] restore
2024-01-06 14:44:12,529 INFO    MainThread:61646 [wandb_run.py:_restore():2191] restore done
2024-01-06 14:45:30,729 INFO    MainThread:61646 [wandb_init.py:init():614] starting backend
2024-01-06 14:45:30,729 INFO    MainThread:61646 [wandb_init.py:init():618] setting up manager
2024-01-06 14:45:30,730 INFO    MainThread:61646 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-01-06 14:45:30,731 INFO    MainThread:61646 [wandb_init.py:init():624] backend started and connected
2024-01-06 14:45:30,736 INFO    MainThread:61646 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-06 14:45:30,736 INFO    MainThread:61646 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-06 14:45:30,736 INFO    MainThread:61646 [wandb_init.py:init():716] updated telemetry
2024-01-06 14:45:30,736 INFO    MainThread:61646 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-01-06 14:46:36,081 WARNING MsgRouterThr:61646 [router.py:message_loop():77] message_loop has been closed
2024-01-06 14:46:36,081 WARNING MsgRouterThr:61646 [router.py:message_loop():77] message_loop has been closed
2024-01-06 14:46:41,120 ERROR   MainThread:61646 [wandb_init.py:init():1188] transport failed
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 752, in init
    result = run_init_handle.wait(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
2024-01-06 14:46:41,255 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-06 14:46:41,255 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Configure stats pid to 61646
2024-01-06 14:46:41,255 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Loading settings from /Users/curtispond/.config/wandb/settings
2024-01-06 14:46:41,255 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Loading settings from /Users/curtispond/Documents/wandb/wandb/settings
2024-01-06 14:46:41,255 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-06 14:46:41,255 INFO    MainThread:61646 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-06 14:46:41,256 INFO    MainThread:61646 [wandb_init.py:_log_setup():524] Logging user logs to /Users/curtispond/Documents/wandb/wandb/run-20240106_144641-yn17vvbw/logs/debug.log
2024-01-06 14:46:41,256 INFO    MainThread:61646 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/curtispond/Documents/wandb/wandb/run-20240106_144641-yn17vvbw/logs/debug-internal.log
2024-01-06 14:46:41,256 INFO    MainThread:61646 [wandb_init.py:init():564] calling init triggers
2024-01-06 14:46:41,256 INFO    MainThread:61646 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning': 'marketing-analytics', 'task': 'classification'}
2024-01-06 14:46:41,256 INFO    MainThread:61646 [wandb_init.py:init():614] starting backend
2024-01-06 14:46:41,256 INFO    MainThread:61646 [wandb_init.py:init():618] setting up manager
2024-01-06 14:46:41,335 ERROR   MainThread:61646 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 619, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 37, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cx-analytics/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
